### ISSUE TITLE
Grid not displaying on Chrome Mac  56.0.2924.87 (64-bit)

### ISSUE THREAD

**Issue by chadpry** [web-tiki/responsive-grid-of-hexagons#17] opened 2017-04-01 17:53 UTC
Here is a screenshot. 

I'm on a MAC OS 10.11.6

![screen shot 2017-04-01 at 1 52 28 pm](https://cloud.githubusercontent.com/assets/194748/24581090/91dd2d4a-16e2-11e7-9151-b1e3271b6eff.png)

**Comment by web-tiki** [comment] 2017-04-03 11:19
Hi @chadpry what browser are you using? 
I have no acces to a MAC so if you could inspect it it would be great.

**Comment by web-tiki** [comment] 2017-04-03 11:29
Hi @chadpry I tested this on crossbrowsertesting.com and I can't reproduce this issue, it works fine. What version of chrome are you using?

If you could inpect the code (maybe the images didn't load for you), it would be great. 
Thx for reporting

**Comment by web-tiki** [comment] 2017-04-26 09:21
As there is no feedback for this issue and I have not been able to reproduce it using the information given, I will close this issue.

**Closed as completed by web-tiki** 2017-04-26 09:21 UTC
