### ISSUE TITLE
Rotate 

### ISSUE THREAD

**Issue by ghost** [web-tiki/responsive-grid-of-hexagons#9] opened 2016-05-25 12:03 UTC
Hello, I'm trying to rotate them 30 degrees so they have a straight top (as per our design instructions).

However, this causes an issue like this:

![hexrotate](https://cloud.githubusercontent.com/assets/6955419/15539185/f473f11e-2278-11e6-85b9-ced9d87714cb.PNG)

What I've done there is update these rotate values:

```
.hex {
    position: relative;
    list-style-type: none;
    float: left;
    overflow: hidden;
    visibility: hidden;
    outline:1px solid transparent; /* fix for jagged edges in FF on hover transition */
    -webkit-transform: rotate(-30deg) skewY(30deg) translatez(-1px);
        -ms-transform: rotate(-30deg) skewY(30deg) translatez(-1px);
            transform: rotate(-30deg) skewY(30deg) translatez(-1px);
}
```

Note the overlapping, bad alignment and the skewed content. 

Can you point me in the right path to rotating the hex and its contents accurately so they all line up but with a straight top?

Much appreciate any guidance.

Thanks.

**Comment by poi33** [comment] 2016-05-26 18:32
The main page does offer some pointer to how you can adjust the hex grid:
[Sizing](https://github.com/web-tiki/responsive-grid-of-hexagons#spacing-and-sizing-calculations)
[Spacing](https://github.com/web-tiki/responsive-grid-of-hexagons#spacing)

When rotating the size is changed so you would have to recalculate;
width, height, margin and padding.

The sizing of the hexagons is done in the media query's they look like this in the css file:
@media (min-width:1201px) 

I hope this helps you on your project,
 but i will **have to close this issue** because the problem is with an alteration of the hexgrid.

**Closed as completed by poi33** 2016-05-26 18:32 UTC
