### ISSUE TITLE
Responsive grid of hexagons not working with Cold fusion header/footer on site

### ISSUE THREAD

**Issue by efitgo** [web-tiki/responsive-grid-of-hexagons#29] opened 2018-10-18 17:45 UTC
I have adjusted hexagon code to fit desired design for my project and migrated the hexagon html/css into my project website code that is using Cold Fusion/bootstrap. When I test hexagon in project website, I see that hexagon hover "shutter" will not completely close and font color on hover "shutter" has changed to grayish color.  It appears there is conflict between website css and hexagon css? What do you suggest? Please help

HTML
```
<!DOCTYPE html>
<html lang="en">
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

      <head>
	<cfinclude template="/head.cfm">
      <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/css/hexgrid1.css">
    <link href='https://fonts.googleapis.com/css?family=Raleway:300' rel='stylesheet' type='text/css'>
</head>

<body>
<cfinclude template="/header.cfm">
<div class="main">
     <div class="introduction">
          <div class="container">
			<h1>Resources</h1>
		</div>
	</div>
    <ul id="hexGrid">
      <li class="hex">
        <div class="hexIn">
          <a class="hexLink" href="https://ceitraining.org/resources/hiv/">
            <img src="../images/shadowblue/hiv shadow.jpg" alt="hiv" />
            <h1>HIV</h1>
            <p>HIV Resources</p>
          </a>
        </div>
      </li>
      <li class="hex">
        <div class="hexIn">
          <a class="hexLink" href="https://ceitraining.org/resources/prep/">
            <img src="../images/shadowblue/prep shadow.jpg" alt="prep" />
            <h1>PrEP</h1>
            <p>PrEP Resources</p>
          </a>
        </div>
      </li>
            <li class="hex">
        <div class="hexIn">
          <a class="hexLink" href="https://ceitraining.org/resources/hcv/">
            <img src="../images/shadowblue/hcv shadow.jpg" alt="hcv" />
            <h1>HCV</h1>
            <p>HCV Resources</p>
          </a>
        </div>
      </li>
            <li class="hex">
        <div class="hexIn">
          <a class="hexLink" href="https://ceitraining.org/std-resources/">
          
            <img src="../images/shadowblue/std shadow.jpg" alt="std" />
            <h1>STD</h1>
            <p>STD Resources</p>
          </a>
        </div>
      </li>
      <li class="hex">
        <div class="hexIn">
          <a class="hexLink" href="https://ceitraining.org/resources/echo/">
            <img src="../images/shadowblue/echo shadow.jpg" alt="echo" />
            <h1>ECHO</h1>
            <p>ECHO Resources</p>
          </a>
        </div>
      </li>
      <li class="hex">
        <div class="hexIn">
          <a class="hexLink" href="https://ceitraining.org/resources/clinical resources/">
            <img src="../images/shadowblue/clinical shadow.jpg" alt="clinical resources" />
            <h1>CEI Clinical</h1>
            <p>CEI Clinical Resources</p>
          </a>
        </div>
      </li>
            <li class="hex">
        <div class="hexIn">
          <a class="hexLink" href="https://ceitraining.org/resources/substance use/">
            <img src="../images/shadowblue/substance shadow.jpg" alt="substance" />
            <h1>Substance Use</h1>
            <p>Substance Use Resources</p>
          </a>
        </div>
      </li>
      <li class="hex">
        <div class="hexIn">
          <a class="hexLink" href="https://ceitraining.org/resources/ai/">
            <img src="../images/shadowblue/ai shadow.jpg" alt="ai" />
            <h1>AIDS Institute</h1>
            <p>AIDS Institute Resources</p>
          </a>
        </div>
      </li>
      <li class="hex">
        <div class="hexIn">
          <a class="hexLink" href="https://ceitraining.org/resources/other/">
            <img src="../images/Shadowblue/other shadow.jpg" alt="other" />
            <h1>Other</h1>
            <p>Other Resources</p>
          </a>
        </div>
      </li>
            <li class="hex">
        <div class="hexIn">
          <a class="hexLink" href="https://ceitraining.org/sp2/index.cfm?action=home.tutorials&section_id=0">
            <img src="../images/shadowblue/tour shadow1.jpg" alt="tour" />
            <h1>Tour</h1>
            <p>MyCEI Tutorial</p>
          </a>
        </div>
      </li>
     <img src="../images/medi folks.jpg" alt="tour" />
    </ul>	
		</div>
                </div>
                                </div>
                               
                               
                            <!--- CONTENT END --->
                        </div>
                    </div>
                </div>
            </div>
            <cfinclude template="/footer.cfm">
    </body>

    </html>

```
CSS
```
* {
    margin: 0;
    padding: 120;
}
body {
    background: rgb(667, 667, 667);
}
#hexGrid {
  display: flex;
  flex-wrap: wrap;
  width: 50%;
  margin: 0 auto;
  overflow: hidden;
  font-family: 'Raleway', sans-serif;
  font-size: 15px;
  list-style-type: none;
}

.hex {
  position: relative;
  visibility:hidden;
  outline:1px solid transparent; /* fix for jagged edges in FF on hover transition */
}
.hex::after{
  content:'';
  display:block;
  padding-bottom: 88.2%;  /* =  100 / tan(60) * 1.5 */
}
.hexIn{
  position: absolute;
  width:96%;
  padding-bottom: 110.851%; /* =  width / sin(60) */
  margin:0 2%;
  overflow: hidden;
  visibility: hidden;
  outline:1px solid transparent; /* fix for jagged edges in FF on hover transition */
  -webkit-transform: rotate3d(0,0,1,-90deg) skewY(30deg);
      -ms-transform: rotate3d(0,0,1,-90deg) skewY(30deg);
          transform: rotate3d(0,0,1,-60deg) skewY(30deg);
}
.hexIn * {
  position: absolute;
  visibility: visible;
  outline:1px solid transparent; /* fix for jagged edges in FF on hover transition */
}
.hexLink {
    display:block;
    width: 100%;
    height: 100%;
    text-align: center;
    color: #fff;
    overflow: hidden;
    -webkit-transform: skewY(-30deg) rotate3d(0,0,1,60deg);
        -ms-transform: skewY(-30deg) rotate3d(0,0,1,60deg);
            transform: skewY(-30deg) rotate3d(0,0,1,60deg);
}

/*** HEX CONTENT **********************************************************************/
.hex img {
  left: -100%;
  right: -100%;
  width: auto;
  height: 100%;
  margin: 0 auto;
  -webkit-transform: rotate3d(0,0,0,0deg);
      -ms-transform: rotate3d(0,0,0,0deg);
          transform: rotate3d(0,0,0,0deg);
}

.hex h1, .hex p {
  width: 100%;
  padding: 5%;
  box-sizing:border-box;
  background-color: rgba(0, 75, 226, 0.8);
  font-weight: 300;
  -webkit-transition:  -webkit-transform .2s ease-out, opacity .3s ease-out;
          transition:          transform .2s ease-out, opacity .3s ease-out;
}
.hex h1 {
  bottom: 50%;
  padding-top:50%;
  font-size: 1.5em;
  z-index: 1;
  -webkit-transform:translate3d(0,-100%,0);
      -ms-transform:translate3d(0,-100%,0);
          transform:translate3d(0,-100%,0);
}
.hex h1::after {
  content: '';
  position: absolute;
  bottom: 0;
  left: 45%;
  width: 10%;
  text-align: center;
  border-bottom: 1px solid #fff;
}
.hex p {
  top: 50%;
  padding-bottom:50%;
  -webkit-transform:translate3d(0,100%,0);
      -ms-transform:translate3d(0,100%,0);
          transform:translate3d(0,100%,0);
}


/*** HOVER EFFECT  **********************************************************************/
.hexLink:hover h1, .hexLink:focus h1,
.hexLink:hover p, .hexLink:focus p{
  -webkit-transform:translate3d(0,0,0);
      -ms-transform:translate3d(0,0,0);
          transform:translate3d(0,0,0);
}

/*** HEXAGON SIZING AND EVEN ROW INDENTATION *****************************************************************/
@media (min-width:1201px) { /* <- 5-4  hexagons per row */
  #hexGrid{
    padding-bottom: 4.4%
  }
  .hex {
    width: 25%; /* = 100 / 5 */
  }
  .hex:nth-child(7n+1){ /* first hexagon of even rows */
    margin-left:12.5%;  /* = width of .hex / 2  to indent even rows */
  }
}

@media (max-width: 1200px) and (min-width:901px) { /* <- 4-3  hexagons per row */
  #hexGrid{
    padding-bottom: 5.5%
  }
  .hex {
    width: 25%; /* = 100 / 4 */
  }
  .hex:nth-child(7n+5){ /* first hexagon of even rows */
    margin-left:12.5%;  /* = width of .hex / 2  to indent even rows */
  }
}

@media (max-width: 900px) and (min-width:601px) { /* <- 3-2  hexagons per row */
  #hexGrid{
    padding-bottom: 7.4%
  }
  .hex {
    width: 33.333%; /* = 100 / 3 */
  }
  .hex:nth-child(5n+4){ /* first hexagon of even rows */
    margin-left:16.666%;  /* = width of .hex / 2  to indent even rows */
  }
}

@media (max-width: 600px) { /* <- 2-1  hexagons per row */
  #hexGrid{
    padding-bottom: 11.2%
  }
  .hex {
    width: 50%; /* = 100 / 3 */
  }
  .hex:nth-child(3n+3){ /* first hexagon of even rows */
    margin-left:25%;  /* = width of .hex / 2  to indent even rows */
  }
}

@media (max-width: 400px) {
    #hexGrid {
        font-size: 13px;
    }
}
```

**Comment by efitgo** [comment] 2018-10-18 18:05
When <cfinclude template="/head.cfm"> is added

**Comment by poi33** [comment] 2018-10-19 08:49
@efitgo Try inspecting html elemts that have the issue, if there are some classes that change the default appearance size etc. 
@web-tiki do we have any insentiv to make it bootstrap compatible? Maybe a branch?

**Comment by web-tiki** [comment] 2018-10-19 11:38
@efitgo This doesn't seem like an issue related to the hexagon grid but rather a CSS conflict. I am closing the issue for this reason. Try inspecting your elements as @poi33 suggested. If you have a live version of your code I can check, please share a link here and please sepcify what browser you are using.

@poi33 There is no bootsrtap compatible version of the grid and I am not planning on making one, you know my love for bootstrap ;) . If someone feels like making one, I'd be glad to review the code though.

**Closed as completed by web-tiki** 2018-10-19 11:38 UTC

**Comment by efitgo** [comment] 2018-10-19 13:28
Does not appear to be html issue because hexagon html/css code are fully
functional when loaded independent of project website.  The hexagon css
does not appear to work well with project website css  which includes use
of cold fusion/bootstrap.

**Comment by efitgo** [comment] 2018-10-19 13:31
I have beginner experience working with bootstrap but will investigate.
What would you suggest as first step to make hexagon bootstrap compatible?

**Comment by web-tiki** [comment] 2018-10-19 13:36
@efitgo The hexagon grid should work in a bootstrap environment. Maybe there are a few bugs to fix caused by possible CSS conflicts. 

What I mean by making the hexagon grid compatible with bootstrap would be to use bootstrap classes when possible and possibly replace some of the hexagon grid CSS by the bootstrap CSS. I am not very familiar with bootstraps so I don't know exactly what needs to be done..

**Comment by efitgo** [comment] 2018-10-19 13:58
When I remove the following cold fusion tag from the html, then the hexagon
fully functions:  <cfinclude template="/head.cfm">
but removing this tag removes the header/footer style format from project
webpage.
